# fly.toml app configuration file generated for ap-datingapp on 2024-01-19T11:30:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ap-datingapp"
primary_region = "dfw"

[build]
  image = "memomartell/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dzim6nsbe"
  CloudinarySettings__ApiKey="818816453248444"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
